#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-push hook"
# npx nx run next:build

# Type checking apps/next
echo "\nType checking apps/next ..."
npx tsc -p apps/next/tsconfig.json --noEmit --incremental
echo "\nType checking apps/remotion ..."
npx tsc -p apps/remotion/tsconfig.json --noEmit --incremental

echo "Finished running pre-push hook"
