import { cleanEnv, str } from 'envalid';
const env = cleanEnv(process.env, {
    TWITCH_CLIENT_ID: str(),
    TWITCH_CLIENT_SECRET: str(),
    DATABASE_URL: str(),
    DB_PASSWORD: str(),
    TWITTER_ID: str(),
    TWITTER_SECRET: str(),
    SECRET: str(),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: str(),
    STRIPE_SECRET_KEY: str(),
    STRIPE_WEBHOOK_SECRET_LIVE: str(),
    STRIPE_WEBHOOK_SECRET: str(),
    EVENTSUB_SECRET: str(),
    APP_DOMAIN: str(),
    ADMINER_URL: str(),
    ANALYTICS_URL: str(),
    REMOTION_URL: str(),
    DO_ACCESS_KEY: str(),
    DO_SECRET: str(),
    DO_SPACE_ENDPOINT: str(),
    REVUE_API_KEY: str(),
    ENABLE_WEBHOOK_LOCAL_TESTING: str(),
    ENABLE_DISCORD_WEBHOOKS: str(),
    DISCORD_WEBHOOK_URL: str(),
    DISCORD_BANNER_DISABLED_WEBHOOK_URL: str(),
    DISCORD_ERROR_WEBHOOK_URL: str(),
    DISCORD_LOGS_WEBHOOK_URL: str(),
    IMAGE_BUCKET_NAME: str(),
    BANNER_BACKUP_BUCKET: str(),
    PROFILE_PIC_BUCKET_NAME: str(),
    PROFILE_PIC_BACKUP_BUCKET: str(),
    PROFILE_PIC_CACHE_BUCKET: str(),
    SERVICE_ENV: str(),
    DISCORD_NEW_SUBSCRIBER_URL: str(),
    DISCORD_CANCELLED_SUBSCRIBER_URL: str(),
    STRIPE_AFFILIATE_COUPON: str(),
    STRIPE_AFFILIATE_WEBHOOK_SECRET: str(),
    STRIPE_DASHBOARD_BASEURL: str(),
    NODEMAILER_API_KEY: str(),
    NODEMAILER_DOMAIN: str(),
    DISCORD_GIFT_PURCHASED_URL: str(),
});

export default env;
